### model
model_name_or_path: Qwen/Qwen2.5-Coder-0.5B

### method
stage: pt
do_train: true
finetuning_type: full
# lora_target: all
# lora_rank: 8

### dataset
dataset: openai_pair
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /scratch/zijd/logs/qwen2.5-coder-0.5B/openai
logging_steps: 10
save_steps: 50
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_dataset: hlsyn_pair_test
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 50